### ISSUE TITLE
Manual Floating-Point proofs with gnatprove and Isabelle 

### ISSUE THREAD

**Issue by rasheedja** [AdaCore/spark2014#13] opened 2019-06-17 21:11 UTC
## Background Info
- I'm running Ubuntu 18.04. 
- SPARK 2019 installed.
- Why3 version 1.2.0.
- Isabelle 2018
- Have setup integration with Why3 and Isabelle (http://why3.lri.fr/doc/itp.html#sec114)

## Description
I'm using SPARK 2019.

When trying to manually prove a verification condition that involves FP numbers with Isabelle, an error is thrown when Isabelle tries to parse the Why3 generated XML file.

![](https://i.imgur.com/hwzJ7cd.png)

From what I can see, the XML file is telling Isabelle to apply is_int to the Real number 1. After some investigation, I found this in \_gnatprove_standard.mlw which may be related?

In module Float32 and Float64
Lines 484-487, and 509-512

```why
  val constant one : t
  ensures { result = (1.0:t) }
  axiom one_is_int: is_int one
  axiom one_of_int: one = of_int RNA 1
```

I've noticed that Why3 throws a warning regarding these axioms when trying to open the IDE.

```
$ why3 -L ~/Research/opt/GNAT/2019/share/spark/theories/ ide gnatprove/test_reals.mlw 
...
File "/home/junaid/Research/opt/GNAT/2019/share/spark/theories/_gnatprove_standard.mlw", line 486, characters 8-18:
warning: axiom one_is_int does not contain any local abstract symbol (contains: t, is_int, one)
File "/home/junaid/Research/opt/GNAT/2019/share/spark/theories/_gnatprove_standard.mlw", line 487, characters 8-18:
warning: axiom one_of_int does not contain any local abstract symbol (contains: int, (=), mode, RNA, t, of_int, one)
File "/home/junaid/Research/opt/GNAT/2019/share/spark/theories/_gnatprove_standard.mlw", line 511, characters 8-18:
warning: axiom one_is_int does not contain any local abstract symbol (contains: t, is_int, one)
File "/home/junaid/Research/opt/GNAT/2019/share/spark/theories/_gnatprove_standard.mlw", line 512, characters 8-18:
warning: axiom one_of_int does not contain any local abstract symbol (contains: int, (=), mode, RNA, t, of_int, one)
...
```

## Minimal Example for Reproduction

The following program will reproduce the issue.

```ada
package Double 
with SPARK_Mode
is
   function Double (X : Float) return Float
     with Pre => 
       X > 0.0 and
       X < 1000.0,
       Post => X + X /= Double'Result; --This is purposefully wrong
end Double;
```

```ada
package body Double 
with SPARK_Mode
is
   function Double (X : Float) return Float is
     (X * 2.0);
end Double;
```

gnatprove will fail to prove `X + X /= Double'Result`, as expected.

At this point, Right-clicking the warning message, running SPARK -> Prove Check, and adding the flag `--prover=isabelle` should open isabelle, as seen in the screenshot posted above.

The same program implemented using Integers will open in Isabelle with no Issue.

The XML file that Isabelle tries to open can be found here `gnatprove/Double__double__pragargs__cmp.xml`.

I've uploaded the minimal example with all generated files to [this GitHub repo](https://github.com/rasheedja/ada_manual_float_proof_bug).

Let me know if you need any more info.

**Comment by claudemarche** [comment] 2019-06-19 11:44
I confirm that I can get the same error when starting directly from an equivalent Why3 file (given below for information) so it is definitely a bug in the translation from Why3 to Isabelle. I will fill a bug report on Why3 site instead.
```
use ieee_float.Float32

let f (x: Float32.t) : Float32.t
   requires { lt (0.0:t) x /\ lt x (1000.0:t) }
   ensures  { not (eq (add RNE x x) result) }
 = mul RNE x (2.0:Float32.t)
```

**Comment by kanigsson** [comment] 2019-07-04 03:04
Thank you Claude, so I am closing this issue here. @rasheedja you can open a new one if the issue persists on the SPARK side even if/when the issue is fixed in why3.

**Closed by kanigsson** 2019-07-04 03:04 UTC

**Comment by claudemarche** [comment] 2019-07-04 09:17
Indeed the issue is already [fixed in Why3](https://gitlab.inria.fr/why3/why3/issues/350)
